name: expenso_expense_tracker
description: "Smart expense tracker."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"







dependencies:
  flutter:
    sdk: flutter



  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  slider_button: ^2.1.0
  easy_localization: ^3.0.7+1
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  build: ^2.4.2
#  card_scanner: ^1.0.2

  drift: ^2.15.0
  path_provider: ^2.1.2
  path: ^1.9.0
  sqlite3_flutter_libs: ^0.5.21
  carousel_slider: ^5.1.1
  flutter_card_swiper: ^7.0.2



dependency_overrides:
  vibration: ^3.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  icon_builder:
    path: ./icon_builder


  build_runner: ^2.4.15
  drift_dev: ^2.15.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  flutter_lints: ^5.0.0






flutter:
  uses-material-design: true

  assets:
    - assets/languages/
    - assets/icons/
    - assets/fonts/



  fonts:
    - family: credit card
      fonts:
        - asset: assets/fonts/credit_card.ttf

    - family: credit card new
      fonts:
        - asset: assets/fonts/Kredit_Back.otf







targets:
  $default:
    builders:
      icon_builder|icon_builder:
        generate_for:
          - lib/generated/icons_placeholder.dart


builders:
  icon_builder:
    import: "package:expenso_expense_tracker/icons_placeholder.dart"







