builders:
  icon_builder:
    import: "package:icon_builder/builder.dart"
    builder_factories: ["iconBuilder"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: none
    build_to: source
